Fix missing zoomed_width in perspective mode
When Settings->Viewer->Use perspective view is checked, printrun
restated and splitter resized an exception is thrown
AttributeError: 'GcodeViewPanel' object has no attribute 'zoomed_width'
Traceback (most recent call last):
  File "gl/panel.py", line 155, in processSizeEvent
    self.OnReshape()
  File "gl/panel.py", line 235, in OnReshape
    factor = min(wratio * self.zoomed_width, hratio * self.zoomed_height)