Put bytes instead of str to CoreFoundation.CFStringCreateWithCString
The exception was:

ValueError: Expecting byte string of length 1, got a 'str'

Yet bytes with any length appears to work, so i assume it is bogus.

Fixes https://github.com/kliment/Printrun/issues/619#issuecomment-383080135